// utils/sendEmail.js
import nodemailer from 'nodemailer';
import { passwordResetEmailTemplate } from "../email_templates/passwordResetEmailTemplate.js"

import dotenv from 'dotenv';

dotenv.config();

const transporter = nodemailer.createTransport({
    service: 'gmail',
    host: "smtp.gmail.com",
    port: 587,
    secure: false,
    auth: {
        user: process.env.EMAIL_USER, // your email
        pass: process.env.EMAIL_PASSWORD  // your email password
    }
});

const sendEmail = async (to, subject, htmlContent, attachments) => {
    try {
        const info = await transporter.sendMail({
            from: {
                name: "OurSpace",
                address: process.env.EMAIL_USER,
            }, // sender address
            to: to, // list of receivers
            subject: subject, // Subject line
            html: htmlContent, // HTML content generated by the template
            attachments: attachments // array of attachments (can be null or empty)
        });

        console.log("Message sent: %s", info.messageId);
    } catch (error) {
        console.error("Error sending email: %s", error);
    }
};

export default sendEmail;
